# Generated by Django 5.1.1 on 2024-09-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_pergunta_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('qtd_acertos', models.IntegerField()),
                ('tempo', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='qa.categoria'),
        ),
    ]
