# Generated by Django 5.1.1 on 2024-09-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_ranking_alter_pergunta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
